"""empty message

Revision ID: 51628226a5ec
Revises: e658302163cd
Create Date: 2019-11-29 19:16:55.584873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51628226a5ec'
down_revision = 'e658302163cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_weight_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_weight_history_id'), 'profile_weight_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_weight_history_id'), table_name='profile_weight_history')
    op.drop_table('profile_weight_history')
    # ### end Alembic commands ###
