"""empty message

Revision ID: 8247d45cbacb
Revises: 33305ee29d35
Create Date: 2020-02-28 19:40:31.057894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8247d45cbacb'
down_revision = '33305ee29d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_goal_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_training_goal_categories_id'), 'training_goal_categories', ['id'], unique=False)
    op.create_table('training_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('start_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['training_goal_categories.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_goals_profile_id'), 'training_goals', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_goals_profile_id'), table_name='training_goals')
    op.drop_table('training_goals')
    op.drop_index(op.f('ix_training_goal_categories_id'), table_name='training_goal_categories')
    op.drop_table('training_goal_categories')
    # ### end Alembic commands ###
