"""empty message

Revision ID: b9dfce251b5a
Revises: b1389b4b0dcf
Create Date: 2020-07-09 13:59:57.850782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9dfce251b5a'
down_revision = 'b1389b4b0dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_workout_categories_id'), 'workout_categories', ['id'], unique=False)
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('climb', sa.Integer(), nullable=False),
    sa.Column('resource_path', sa.String(length=255), nullable=True),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['workout_categories.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_path')
    )
    op.create_index(op.f('ix_workouts_profile_id'), 'workouts', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workouts_profile_id'), table_name='workouts')
    op.drop_table('workouts')
    op.drop_index(op.f('ix_workout_categories_id'), table_name='workout_categories')
    op.drop_table('workout_categories')
    # ### end Alembic commands ###
