"""empty message

Revision ID: e2cfd1382448
Revises: b9dfce251b5a
Create Date: 2020-07-16 18:23:37.683552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2cfd1382448'
down_revision = 'b9dfce251b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_categories', sa.Column('supports_gps_data', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_categories', 'supports_gps_data')
    # ### end Alembic commands ###
