"""empty message

Revision ID: efd88a3c30a8
Revises: edf37629d0f4
Create Date: 2020-08-23 12:34:41.656176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd88a3c30a8'
down_revision = 'edf37629d0f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polar_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=24), nullable=False),
    sa.Column('polar_user_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=True),
    sa.Column('access_token', sa.String(length=64), nullable=True),
    sa.Column('access_token_expires', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    op.create_index(op.f('ix_polar_users_profile_id'), 'polar_users', ['profile_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_polar_users_profile_id'), table_name='polar_users')
    op.drop_table('polar_users')
    # ### end Alembic commands ###
